eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.3.22:8761/eureka/
      
server:
  port: 8762
  
spring:
  application:
    name: eshop-product-service
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
    url: jdbc:mysql://192.168.3.20:3306/eshop
    username: root
    password: root
  rabbitmq:
    host: 192.168.3.20
    port: 5672  
    username: rabbitadmin  
    password: 123456